import { NextRequest, NextResponse } from "next/server";

/**
 * Custom API route for streaming chat SSE responses.
 *
 * The Next.js rewrites() proxy in next.config.ts may buffer the response body
 * before forwarding it to the browser. In that case, SSE events generated by
 * the backend never reach the client incrementally and the connection can be
 * closed by an idle timeout (commonly ~30s).
 *
 * This route takes priority over the rewrite rule and pipes the backend
 * ReadableStream directly to the client without buffering.
 */

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Allow long-running LLM streams.
export const maxDuration = 300;

const BACKEND_URL = process.env.INTERNAL_API_URL || "http://localhost:8000";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ notebookId: string }> }
) {
  const { notebookId } = await params;
  const targetUrl = `${BACKEND_URL}/api/v1/chat/notebooks/${notebookId}/chat/stream`;

  try {
    // Chat request JSON is small; buffering request body here is acceptable.
    const bodyText = await request.text();

    const backendResponse = await fetch(targetUrl, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        accept: "text/event-stream",
      },
      body: bodyText,
      cache: "no-store",
      signal: request.signal,
    });

    // For non-2xx or missing body, forward as normal HTTP response.
    if (!backendResponse.ok || !backendResponse.body) {
      const errorText = await backendResponse.text();
      return new NextResponse(errorText, {
        status: backendResponse.status,
        headers: {
          "content-type":
            backendResponse.headers.get("content-type") || "application/json",
          "cache-control":
            backendResponse.headers.get("cache-control") || "no-cache, no-store",
        },
      });
    }

    // Pipe the backend ReadableStream directly to the browser. Do not read it.
    return new Response(backendResponse.body, {
      status: backendResponse.status,
      headers: {
        "content-type":
          backendResponse.headers.get("content-type") || "text/event-stream; charset=utf-8",
        "cache-control":
          backendResponse.headers.get("cache-control") || "no-cache, no-transform",
        "x-accel-buffering": backendResponse.headers.get("x-accel-buffering") || "no",
        connection: backendResponse.headers.get("connection") || "keep-alive",
      },
    });
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") {
      // Client disconnected or replaced the request while streaming.
      return new NextResponse(null, { status: 499 });
    }

    console.error("[SSE proxy] stream proxy error:", error);
    return NextResponse.json(
      {
        error_code: "E_STREAM_PROXY",
        message:
          error instanceof Error
            ? error.message
            : "Failed to proxy SSE stream to backend",
      },
      { status: 502 }
    );
  }
}
