import { NextRequest, NextResponse } from "next/server";

/**
 * Custom API route for streaming chat SSE responses.
 *
 * The Next.js rewrites() proxy in next.config.ts may buffer the response body
 * before forwarding it to the browser. In that case, SSE events generated by
 * the backend never reach the client incrementally and the connection can be
 * closed by an idle timeout (commonly ~30s).
 *
 * This route takes priority over the rewrite rule and pipes the backend
 * ReadableStream directly to the client without buffering.
 *
 * NOTE: We intentionally avoid passing `request.signal` directly to the
 * backend fetch. In Next.js App Router dev mode, the incoming request signal
 * can enter an inconsistent state (due to HMR / turbopack lifecycle), causing
 * the internal fetch to hang indefinitely. Instead we create our own
 * AbortController and wire the client disconnect to it manually.
 */

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Allow long-running LLM streams.
export const maxDuration = 300;

function getBackendUrl(): string {
  return (process.env.INTERNAL_API_URL || "http://127.0.0.1:8000").trim();
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ notebookId: string }> },
) {
  const { notebookId } = await params;
  const targetUrl = `${getBackendUrl()}/api/v1/chat/notebooks/${notebookId}/chat/stream`;

  console.log("[SSE proxy] route entered, notebookId=%s", notebookId);

  // Manual abort controller — avoids passing request.signal directly to fetch.
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 300_000); // 5 min

  // If the client disconnects, cancel the backend request.
  const onClientAbort = () => controller.abort();
  request.signal.addEventListener("abort", onClientAbort);

  try {
    const bodyText = await request.text();
    console.log("[SSE proxy] request body read (%d bytes)", bodyText.length);

    console.log("[SSE proxy] backend fetch start -> %s", targetUrl);
    const backendResponse = await fetch(targetUrl, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        accept: "text/event-stream",
      },
      body: bodyText,
      cache: "no-store",
      signal: controller.signal,
    });
    console.log("[SSE proxy] backend response received, status=%d", backendResponse.status);

    // For non-2xx or missing body, forward as normal HTTP response.
    if (!backendResponse.ok || !backendResponse.body) {
      const errorText = await backendResponse.text();
      return new NextResponse(errorText, {
        status: backendResponse.status,
        headers: {
          "content-type":
            backendResponse.headers.get("content-type") || "application/json",
          "cache-control":
            backendResponse.headers.get("cache-control") || "no-cache, no-store",
        },
      });
    }

    console.log("[SSE proxy] streaming to client...");

    // Pipe the backend ReadableStream directly to the browser.
    return new Response(backendResponse.body, {
      status: backendResponse.status,
      headers: {
        "content-type":
          backendResponse.headers.get("content-type") || "text/event-stream; charset=utf-8",
        "cache-control":
          backendResponse.headers.get("cache-control") || "no-cache, no-transform",
        "x-accel-buffering": backendResponse.headers.get("x-accel-buffering") || "no",
        connection: backendResponse.headers.get("connection") || "keep-alive",
      },
    });
  } catch (error) {
    if (error instanceof Error && error.name === "AbortError") {
      console.log("[SSE proxy] aborted (client disconnect or timeout)");
      return new NextResponse(null, { status: 499 });
    }

    console.error("[SSE proxy] stream proxy error:", error);
    return NextResponse.json(
      {
        error_code: "E_STREAM_PROXY",
        message:
          error instanceof Error
            ? error.message
            : "Failed to proxy SSE stream to backend",
      },
      { status: 502 },
    );
  } finally {
    clearTimeout(timeout);
    request.signal.removeEventListener("abort", onClientAbort);
  }
}
