"""Diagram domain entity."""

from dataclasses import dataclass, field
from typing import Optional

from newbee_notebook.domain.entities.base import Entity, generate_uuid


@dataclass
class Diagram(Entity):
    """A notebook-scoped diagram generated by runtime tools."""

    diagram_id: str = field(default_factory=generate_uuid)
    notebook_id: str = ""
    title: str = ""
    diagram_type: str = ""
    format: str = ""
    content_path: str = ""
    document_ids: list[str] = field(default_factory=list)
    node_positions: Optional[dict[str, dict[str, float]]] = None
